"""new migration

Revision ID: 44090dd09450
Revises: 
Create Date: 2020-10-02 10:06:04.344613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44090dd09450'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quizquestions1',
    sa.Column('question', sa.String(), nullable=False),
    sa.Column('option1', sa.String(), nullable=False),
    sa.Column('option2', sa.String(), nullable=False),
    sa.Column('option3', sa.String(), nullable=False),
    sa.Column('option4', sa.String(), nullable=False),
    sa.Column('answer', sa.String(), nullable=False),
    sa.Column('creatorid', sa.String(), nullable=False),
    sa.Column('questionid', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('difficulty', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('questionid')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('username', sa.String(length=1000), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('bio', sa.String(length=255), nullable=True),
    sa.Column('profile_pic_path', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('answered', sa.PickleType(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('roles')
    op.drop_table('quizquestions1')
    # ### end Alembic commands ###
